### ISSUE TITLE
Undergraduate Page - Resources

### ISSUE THREAD

**Issue by chinathaip** [stamford-syntax-club/stamfordcenter-frontend#25]
## Where is this page
Undergraduate
|__ Resources

basically it is a drop-down

### Design

@nunmanasm
https://www.figma.com/file/3ZIqknEOxFi30PHdvlrQad/Stamford-Center?type=design&node-id=0%3A1&mode=design&t=yclmkutc6qRRwimX-1

### Page Content
- [x] Class Schedules & Full Name Lists
- [x] Academic Calendars
- [x] Add/Drop/Change section Information (How to)
- [x] Exam Timetables
- [x] Advisors List
- [x] Microsoft Office 365
- [x] Forms
- [x] Van Schedules
- [x] Visa Policy Update - Visa Cancellation Announcement
- [x] Insurance Information
- [x] Student Handbook
- [x] Study Plans (All curriculum files) (The existing study plans page should be moved here)

## Tasks
**Frontend:**
- Call API from backend to retrieve lists of files in this page and display it
    - `https://center-be.stamford.dev/api/resources/resources`
- When user clicks on the the item, call API to get file: `response[index].files[index].url`

**Response:** 
```json
[
  {
    "name": "Class Schedules & Full Name Lists",
    "iconURL": "https://center-be.stamford.dev/api/files/resources/class_schedules_icon.png",
    "files": [
      {
        "name": "UG Class Schedule Term 1-2023",
        "url": "https://center-be.stamford.dev/api/files/resources/1_2023_class_schedule.pdf"
      }
    ]
  },
  {
    "name": "Academic Calendars",
    "iconURL": "https://center-be.stamford.dev/api/files/resources/academic_calendars_icon.png",
    "files": [
      {
        "name": "Academic Calendar Term 1-2023",
        "url": "https://center-be.stamford.dev/api/files/resources/1_2023_academic_calendar.pdf"
      },
      {
        "name": "Academic Calendar Term 2-2023",
        "url": "https://center-be.stamford.dev/api/files/resources/2_2023_academic_calendar.pdf"
      }
    ]
  },
 // more
]
```
